-- =============================================================================
-- Tabel public.kituri_feronerie — prețuri kit feronerie (Naturen) per kit × toc × decor
-- Rulează în Supabase → SQL Editor.
-- Apoi: py utils/scripts/import_kituri_feronerie_supabase.py
-- =============================================================================

create table if not exists public.kituri_feronerie (
  id bigint generated by default as identity primary key,
  kit text not null,
  tip_toc text not null,
  decor text not null,
  pret_eur_fara_tva double precision not null default 0,
  descriere_feronerie text not null default '',
  created_at timestamptz default now()
);

comment on table public.kituri_feronerie is
  'Kit feronerie exterior: preț listă EUR fără TVA per combinație kit, tip toc, decor finisaj.';

create index if not exists idx_kituri_feronerie_kit on public.kituri_feronerie (kit);
create index if not exists idx_kituri_feronerie_kit_toc on public.kituri_feronerie (kit, tip_toc);

create unique index if not exists uq_kituri_feronerie_natural
  on public.kituri_feronerie (kit, tip_toc, decor, descriere_feronerie);

alter table public.kituri_feronerie enable row level security;

drop policy if exists "kituri_feronerie_select_anon" on public.kituri_feronerie;
create policy "kituri_feronerie_select_anon"
  on public.kituri_feronerie for select
  to anon, authenticated
  using (true);

notify pgrst, 'reload schema';
