-- =============================================================================
-- Tabel public.dimensiuni_tocuri — dimensiuni deschidere (lățime/înălțime) per tip toc × material × lățime foaie
-- Rulează în Supabase → SQL Editor (o singură dată).
-- Apoi: py utils/scripts/import_dimensiuni_tocuri_supabase.py
-- =============================================================================

create table if not exists public.dimensiuni_tocuri (
  id bigint generated by default as identity primary key,
  tip_toc text not null,
  material_toc text not null,
  latime_foaie_de_usa text not null,
  latime_deschidere text not null,
  inaltime_deschidere text not null,
  created_at timestamptz default now()
);

comment on table public.dimensiuni_tocuri is
  'Dimensiuni nominale deschidere (mm) pentru tocuri: combinație unică tip toc, material, lățime foaie ușă.';

create unique index if not exists uq_dimensiuni_tocuri_natural
  on public.dimensiuni_tocuri (tip_toc, material_toc, latime_foaie_de_usa);

create index if not exists idx_dimensiuni_tocuri_tip on public.dimensiuni_tocuri (tip_toc);

alter table public.dimensiuni_tocuri enable row level security;

drop policy if exists "dimensiuni_tocuri_select_anon" on public.dimensiuni_tocuri;
create policy "dimensiuni_tocuri_select_anon"
  on public.dimensiuni_tocuri for select
  to anon, authenticated
  using (true);

-- service_role (cheie din scripturi) ocolește RLS — nu e nevoie de policy separată pentru import.

notify pgrst, 'reload schema';
