-- Ruleaza in Supabase SQL Editor
-- Creeaza toate tabelele necesare aplicatiei (cloud-only)

create table if not exists public.schema_version (
  version bigint primary key
);

create table if not exists public.sync_state (
  id bigint primary key check (id = 1),
  data_version bigint not null default 0,
  last_sync_at text
);

create table if not exists public.clienti (
  id bigint generated by default as identity primary key,
  nume text,
  telefon text,
  adresa text,
  data_creare text,
  email text
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  nume_complet text not null,
  username text not null unique,
  password_hash text not null,
  approved integer not null default 0,
  created_at text,
  can_modify_curs integer default 1,
  max_discount integer default 15,
  can_delete_offers integer default 1,
  can_delete_clients integer default 0,
  blocked integer default 0,
  can_dev_mode integer default 0,
  telefon_contact text default ''
);

create table if not exists public.produse (
  id bigint generated by default as identity primary key,
  categorie text,
  furnizor text,
  colectie text,
  model text,
  decor text,
  tip_toc text,
  dimensiune text,
  pret double precision,
  finisaj text default '',
  este_izolatie integer default 0
);

create table if not exists public.izolatiile (
  id bigint generated by default as identity primary key,
  denumire text,
  culoare text,
  grosime text,
  dimensiune text,
  pret double precision
);

create table if not exists public.oferte (
  id bigint generated by default as identity primary key,
  id_client bigint references public.clienti(id) on delete set null,
  detalii_oferta text,
  total_lei double precision,
  data_oferta text,
  nume_client_temp text,
  utilizator_creat text,
  discount_proc integer default 0,
  curs_euro double precision,
  avans_incasat integer default 0,
  safe_mode_enabled integer default 1
);

create index if not exists idx_produse_cat_furn on public.produse (categorie, furnizor);
create index if not exists idx_produse_cat_furn_colectie on public.produse (categorie, furnizor, colectie);
create index if not exists idx_oferte_id_client on public.oferte (id_client);
create index if not exists idx_oferte_nume_client_temp on public.oferte (nume_client_temp);
